name: image-insights

on:
  # The schedule will trigger at 0900 UTC timezone
  # schedule:
  #   - cron: "0 07 * * *"V
  push:
    branches:
      - main

permissions:
  packages: write
  contents: write
  id-token: write
# actions: wrgccte
# pull-requests: write

jobs:
  publish-insights:
    env:
      REGISTRY: ghcr.io
      ORG: open-containers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: ansible

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: "0"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3

      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Login to Github Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT}}

      - name: Cache Docker layers
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Collect Provenance
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.ORG }}/${{ matrix.image.name }}:v1.0.0 \
            --format '{{ json .Provenance.SLSA }}' > ./${{ matrix.image.name }}-attestations/${{ matrix.image.name }}-provenance.json

      - name: Collect SBOM
        run: |
          docker buildx imagetools inspect ${{env.REGISTRY}}/${{ env.ORG }}/${{ matrix.image.name }}:v1.0.0 \
            --format '{{ json .SBOM.SPDX }}' > ./${{ matrix.image.name }}-attestations/${{ matrix.image.name }}-sbom.json

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: image
          image-ref: ${{env.REGISTRY}}/${{ env.ORG }}/${{ matrix.image.name }}:v1.0.0
          format: "json"
          output: ./${{ matrix.image.name }}-attestations/${{ matrix.image.name }}-cves.json
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GHCR_PAT }}

      - name: Export SBOM in markdown
        run: |
          go run ./insights_scripts/main.go -sbom ./ansible-attestations/ansoble-sbom.sbom

      - name: Zip and Base64 Encode Attestation Files
        run: |
          zip -r ${matrix.image.name}-attestations.zip ./${matrix.image.name}-attestations
          base64 -w0 ${matrix.image.name}-attestations.zip > ${matrix.image.name}-attestations.b64

      - name: Commit Provenance File to Repository
        run: |
          git config --global user.name "enggithubbot"
          git config --global user.email "intelopsgithubbot@gmail.com"
          git add ./${{ matrix.image.name }}-attestations
          gh api graphql \
            -F githubRepository="${{ env.ORG }}/${{ matrix.image.name }}" \
            -F branchName="${{ matrix.image.name }}-${{ github.run_number }}" \
            -F expectedHeadOid="$(git rev-parse HEAD)" \
            -F commitMessage="Add ansible attestation files" \
            -F files[][path]="${{ matrix.image.name }}-attestations.b64" \
            -F files[][contents]="$(cat ${matrix.image.name}-attestations.b64)" \
            -F 'query=@.github/api/create-commit-on-branch.gql'

        env:
          GH_TOKEN: ${{ secrets.GHCR_PAT }}
